### ISSUE TITLE
[Mobile] Text getting cut off in search bar

### ISSUE THREAD

**Issue by LunarDev-git** [MoonstruckSpirit/MoonstruckSpirit.github.io#4]
# Information

![firefox_Chzb59TlbL](https://github.com/MoonstruckSpirit/P3-Booki/assets/105180230/15e4cf2f-b00c-457a-81e5-3c5d787f9c11)

This is due to a whitespace text only node and I have no idea how to remove it. It doesn't just happen in mobile but the text cuts off only in mobile because of how the search bar is implemented

![firefox_93bTPSYr77](https://github.com/MoonstruckSpirit/P3-Booki/assets/105180230/bc6a9512-8e1f-4e9d-9322-052d63777c53)

**Comment by MoonstruckSpirit** [comment]
Partially fixed but did not remove whitespace
